"""new rules on delete

Revision ID: 5919d3ff0baf
Revises: 8701f50c6869
Create Date: 2024-06-07 01:45:58.689525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5919d3ff0baf'
down_revision: Union[str, None] = '8701f50c6869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('reports_place_id_fkey', 'reports', type_='foreignkey')
    op.drop_constraint('reports_user_id_fkey', 'reports', type_='foreignkey')
    op.create_foreign_key(None, 'reports', 'places', ['place_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'reports', 'employees', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.drop_constraint(None, 'reports', type_='foreignkey')
    op.create_foreign_key('reports_user_id_fkey', 'reports', 'employees', ['user_id'], ['id'])
    op.create_foreign_key('reports_place_id_fkey', 'reports', 'places', ['place_id'], ['id'])
    # ### end Alembic commands ###
