"""added nulluble=true for column place_id in table reports

Revision ID: 8b46e8cbd49d
Revises: 5919d3ff0baf
Create Date: 2024-09-13 11:05:34.158926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b46e8cbd49d'
down_revision: Union[str, None] = '5919d3ff0baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reports', 'place_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
